<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/


// default generated by laravel
// Route::middleware('auth:api')->get('/user', function (Request $request) {
//     return $request->user();
// });

Route::group([
    'prefix' => 'auth',
    'namespace' => 'Auth',
    'middleware' => 'api'
], function(){
    //cukup nama controller saja tidak perlu @ dan nama method, karena controller menggunakan __invoke (memanggil object seperti fungsi). dan controller hanya digunakan untuk satu fungsi saja. 
    Route::post('register', 'RegisterController');
    Route::post('regenerate-otp-code', 'RegenerateOtpCodeController');
    Route::post('verification', 'VerificationController');
    Route::post('update-password', 'UpdatePasswordController');
    Route::post('login', 'LoginController');
});

Route::group([
    'prefix' => 'profile',
    'namespace' => 'User',
    'middleware' => ['email_verified', 'auth:api']
], function(){
    // Route::get('test', function () {
    //     return response()->json([
    //         'message' => 'test auth token'
    //     ]);
    // });
    Route::get('show', 'ProfileController@index');
    Route::post('update', 'ProfileController@update');
});

Route::group([
    'middleware' => 'api',
    'prefix' => 'campaign'
], function(){
    Route::get('random/{count}', 'CampaignController@random');
    Route::post('store', 'CampaignController@store');
    Route::get('/', 'CampaignController@index');
    Route::get('/{id}', 'CampaignController@detail');
    Route::get('/search/{keyword}', 'CampaignController@search');
});

Route::group([
    'middleware' => 'api',
    'prefix' => 'blog'
], function(){
    Route::get('random/{count}', 'BlogController@random');
    Route::post('store', 'BlogController@store');
});